plugins { id 'com.android.application' }

android {
    namespace 'es.renfemonitor'
    compileSdk 35

    defaultConfig {
        applicationId 'es.renfemonitor'
        minSdk 26
        targetSdk 34
        versionCode 44
        versionName '2.1'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
}
